UpCloudLtd/upcloud-csi

deploy/kubernetes/setup-upcloud-csi.yaml

Sidecar container `csi-node-driver-registrar` doesn't contain `bin/sh` command. 
[Socket is removed by node driver registrar](https://github.com/kubernetes-csi/node-driver-registrar/pull/61).
This can be observed by copying `PreStop` hook to `PostStart` and check logs `kubectl -n kube-system describe pods/csi-upcloud-node...`

fix(deploy): remove node driver registrar preStop hook

---

.github/workflows/test.yaml
Makefile
driver/controller.go
driver/controller_test.go
driver/driver.go
driver/node.go
driver/node_test.go
driver/test_utils.go
driver/upcloud.go

- add volume expansion constraints - only offline expansion is supported
- remove unused code
- add test workflow
This will cause driver to report errors if volume is published on node:
`
resize volume "pvc-xyz" by resizer "storage.csi.upcloud.com" failed: rpc error: code = FailedPrecondition desc = volume is currently published on a node
Unable to expand default/xyz because CSI driver storage.csi.upcloud.com only supports offline expansion and volume is currently in-use
`
When volume is unpublished volume resize will succeed:
`
External resizer is resizing volume pvc-xyz
Resize volume succeeded
`

fix(driver): add volume expansion constraints

---

.github/workflows/test.yaml
driver/mounter.go
driver/mounter_test.go
driver/node.go
driver/node_test.go

Test mounter disk and filesystem operations. 
Testing mount points requires root privileges so changed driver workflow to be run using sudo.

chore(driver): refine mounter tests

---

cmd/upcloud-csi-plugin/main.go
driver/controller.go
driver/driver.go
driver/log.go
driver/mounter.go
driver/mounter_test.go
driver/node.go
driver/objgen/objgen.go
driver/upcloud.go

- replace old error middleware (interceptor) with new log middleware
- add correlation ID and GRPC method name to log entries
- remove redundant log entries
- make log level configurable
- use context version of exec.Command in mounter
Correlation ID can be used to link log entries from controller and node. 
For example:
```
$ kubectl -n kube-system logs statefulsets/csi-upcloud-controller csi-upcloud-plugin | grep ControllerPublishVolume
time="2022-10-04T07:02:49Z" level=info msg="request /csi.v1.Controller/ControllerPublishVolume" correlation_id=e29eb9dbd778 hostname=csi-upcloud-controller-0 method=/csi.v1.Controller/ControllerPublishVolume node_id=kubernetes region=fi-hel1
...
$ kubectl -n kube-system logs daemonsets/csi-upcloud-node csi-upcloud-plugin | grep …
```

chore(logging): refine structured logging

---

.goreleaser.yaml
cmd/upcloud-csi-manifest/main.go

CRD objects should be available before applying rest of the objects so that `no matches for kind` errors can be avoided.
This will attach `upcloud-csi-crd.yaml` and `upcloud-csi-setup.yaml` to releases.

refactor(release): deploy CRDs separately

---

.goreleaser.yaml

It seems that hook commands need to be defined one by one. Otherwise for example in this case `temp` directory is not created and releases will fail with `open ./temp/upcloud-csi-crd.yaml: no such file or directory` .

fix(goreleaser): create temp dir in its own hook step

---

README.md

Currently the YAML files referenced in README give 404 errors due to missing branch name in the URL.

Add missing branch name to sample manifest links in README

---

driver/driver.go
driver/identity.go
driver/mounter.go
driver/mounter_test.go
driver/node.go
driver/node_test.go

- fix: volume publish returned error if node host udev event queue was busy
- refactor: return error instead of empty string if volume ID cannot be mapped to block device
- chore: remove format logic in volume context that is not currently supported
- refactor: remove obsolete Mounter interface and unused methods from mounter type
- chore: remove obsolete log messages from identity methods

fix(driver): wait udev before publishing volume

---

cmd/upcloud-csi-plugin/main.go

While CLI arguments work, the username and password values are visible to anyone that can get a process list. Further, some control planes (Kubernetes, Mesos, among others), log the CLI arguments to stderr which would then include the UpCloud username and password.
This PR makes it possible to specify those values via environment variables if they aren't provided in the CLI.

Ability to retrieve username and password from the environment

---

driver/driver.go
driver/filesystem_utils.go

Currently `udevadm` is missing from our images . Running it inside container is not that straight forward or at least it should be investigated more. For now, use it only if is available.  Our `getBlockDeviceByDiskID` still tries to wait `udevDiskTimeout` seconds to disk to appear after attaching.

fix(driver): use udevadm only if available

---

deploy/kubernetes/setup-upcloud-csi.yaml

By default it is better to avoid CSI plugin to run on top of the master-nodes. In case it needed, can be adjusted easily.

avoid master nodes by CSI node plugin

---

.github/workflows/deploy.yml
Makefile
cmd/upcloud-csi-plugin/Dockerfile
go.mod

- bump Go version from 1.17 to .1.19
- use `alpine` image instead of `golang:alpine` to make images smaller

chore(build): use Go 1.19 and alpine:3.17 base image

---

Makefile
driver/node.go

`NodeUnpublishVolume` and `NodeUnstageVolume` should also remove target path, which can be either file or directory (depending on access type).

fix(driver): remove target path when unstaging/unpublishing a volume

---

deploy/kubernetes/setup-upcloud-csi.yaml

Remove `--username` and `--password` command-line flags from Kubernetes deployment manifest. 
Driver can use [environment variables](https://github.com/UpCloudLtd/upcloud-csi/blob/dd4b96549402e847bac7a77f29a7790965c92a90/deploy/kubernetes/setup-upcloud-csi.yaml#L132-L141) directly. This also hides credentials from showing up in process listing.

chore(deploy): use credentials from environment variables

---

Makefile
cmd/upcloud-csi-plugin/main.go
cmd/upcloud-csi-plugin/main_test.go
driver/controller.go
driver/controller_internal_test.go
driver/driver.go
driver/filesystem_internal_test.go
driver/healthcheck.go
driver/identity.go
driver/node.go
driver/node_internal_test.go
driver/service.go
driver/service_internal_test.go
driver/test_utils.go
driver/version.go
go.mod
go.sum
test/integration/sanity/sanity_test.go

- update UpCloud Go API to v6.0.0
- add new `--zone` flag that can be used to set zone when fetching zone using node name is not possible
- add new `--label` flag which can be used to apply default labels to all storages created by the driver
- clean up `Driver` type, fix linting problems and naming conventions
- try graceful shutdown when possible
- change default log level from warning to info

refactor(driver): add new parameters and clean up code

---

.github/workflows/lint.yaml
.pre-commit-config.yaml
driver/filesystem.go

Update to latest golangci-lint and fix linter error in `driver/filesystem.go`:
`assigned to exitCode, but reassigned without using the value (wastedassign)`

chore(lint): update golangci-lint to v1.52.2

---

DEVELOPING.md
driver/controller.go
driver/node.go
driver/service.go
driver/test_utils.go

- increase maximum number of volumes per node from 7 to 14
- return `codes.ResourceExhausted` if disk device limit has been reached

fix(driver): check if maximum number of attached devices has been reached

---

driver/controller.go
driver/service.go

Return OK response if volume is already detached or missing from the node.
This updates [ControllerUnpublishVolume](https://github.com/container-storage-interface/spec/blob/master/spec.md#controllerunpublishvolume) to align with the spec:
> This operation MUST be idempotent. If the volume corresponding to the volume_id is not attached to the node corresponding to the node_id, the Plugin MUST reply 0 OK

fix(driver): update ControllerUnpublishVolume error handling

---

internal/filesystem/filesystem_internal_test.go
internal/filesystem/linux_filesystem.go
internal/plugin/config/config.go
internal/plugin/plugin.go

As supported filesystem types might differ depending on host system this change allows us to narrow down, what types are actually supported. Did also some rework on filesystem tests, so that actual test functions are defined first.

feat(filesystem): check if filesystem type is supported before format

---

internal/filesystem/filesystem_internal_test.go
internal/filesystem/linux_filesystem.go
internal/filesystem/linux_utils.go
internal/plugin/plugin.go
internal/plugin/plugin_internal_test.go
internal/service/upcloud_service.go

- make filesystem formating idempotent
- check that all system tools are available when creating new Linux filesystem instance
- wait until server is in `started` state when attaching and detaching storage devices
- improve filesystem error reporting

fix(filesystem): make filesystem formating idempotent

---

Makefile
internal/controller/controller.go
internal/service/mock/upcloud_client.go
internal/service/service_test.go
internal/service/upcloud_service.go

Run only single attach/detach operation simultaneously per node.  
CSI attacher sidecar runs multiple goroutines (10 by default) that handle volume attachments and that will lead many `SERVER_STATE_ILLEGAL` errors when driver tries to do those operations concurrently towards the same node.  Those operations succeed eventually but those cause unnecessary load to backend and increased pod deployment times. 
This PR tries to solve that problem by using mutex lock per node when executing `ControllerPublishVolume` and `ControllerUnpublishVolume` methods.

fix(service): run only single attach/detach operation simultaneously

---

CHANGELOG.md
internal/controller/controller.go

This aligns `ControllerUnpublishVolume` with the [spec](https://github.com/container-storage-interface/spec/blob/master/spec.md#controllerunpublishvolume)  
> If the volume corresponding to the volume_id or **the node corresponding to node_id cannot be found** by the Plugin and the volume can be safely regarded as ControllerUnpublished from the node, the plugin SHOULD return 0 OK

fix(controller): regard volume as unpublished from the node, if node is not found

---

CHANGELOG.md
internal/controller/controller.go

This adds possibility to use snapshots, taken from non-encrypted volume, as data source for encrypted volume.

feat(controller): allow any snapshot as volume data source for encrypted volume
